- uses: google-github-actions/deploy-cloudrun@v3
  with:
    service: ${{ env.SERVICE }}
    region: ${{ env.REGION }}
    image: ${{ env.IMAGE }}
    flags: >-
      --min-instances=0
      --max-instances=3
      --memory=512Mi
      --cpu=1
      --concurrency=80